#page title
page_title: # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 6751507698 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: pl # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link:
# Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
# Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/appicon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Personalized box breathing for a peaceful mind.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Mateusz Byrtus
your_link: https://x.com/ByrtusMateusz
your_city: Warsaw, Poland
email_address: mateusz.byrtus@icloud.com
facebook_username:
instagram_username:
twitter_username: ByrtusMateusz
github_username: mateusz0909
youtube_username:
mastodon_link:

# Feature List
features:
  - title: Guided Box Breathing
    description: Follow a proven four-step breathing cycle (inhale, hold, exhale, hold) with on-screen cues and customizable timings.
    fontawesome_icon_name: calendar-check

  - title: Haptic & Audio Feedback
    description: Feel each breath with gentle haptic pulses and optional nature or music soundtracks for deeper immersion.
    fontawesome_icon_name: heartbeat

  - title: Custom Session Templates
    description: Save your favorite session settings—breath counts, hold durations, and audio mix—for one-tap repeatability.
    fontawesome_icon_name: save

  - title: Apple Watch Sync
    description: Bring guided breathing on your wrist—start, pause, and track sessions right from your Apple Watch.
    fontawesome_icon_name: watch

  - title: HealthKit Integration
    description: Log sessions automatically in HealthKit to track mindful minutes and view breathing metrics alongside other health data.
    fontawesome_icon_name: apple

  - title: Daily Reminders & Streaks
    description: Set custom notifications to build a consistent practice and earn streak badges as motivation.
    fontawesome_icon_name: bell

  - title: Dark & Light Themes
    description: Match your mood or system appearance with beautiful light and dark color schemes for distraction-free sessions.
    fontawesome_icon_name: adjust

  - title: Favorites & Quick Launch
    description: Bookmark your go-to sessions for instant access from the home screen or widget.
    fontawesome_icon_name: star

  - title: Sleep & Relaxation Mode
    description: Wind down with extended exhale emphasis, soothing background audio, and gentle screen dimming for bedtime routines.
    fontawesome_icon_name: moon

  - title: Multi-Voice Narration
    description: Choose from diverse guided voice packs—male, female, whisper, or nature ambient narrators—for a personalized experience.
    fontawesome_icon_name: users

  - title: Offline & Low-Connectivity Support
    description: All core breathing sessions and premium audio tracks are stored on device for uninterrupted practice anywhere.
    fontawesome_icon_name: wifi-slash

  - title: Progress Dashboard
    description: Visualize weekly and monthly trends in session frequency, duration, and breathing consistency to stay on track.
    fontawesome_icon_name: chart-

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
